### PR TITLE
Brexit joke

### PR DESCRIPTION
**Pull request by AndyGee**
Feel free to close ;-)

### CODE REVIEW

**Comment by TimothyJones** [comment]
Thanks for the PR!

I’m not against jokes in documentation, but I think this one might distract from the point of the quote a bit.

Also, I think the example is a direct quote from the dictionary that’s linked.

If others think it’s an improvement, we could merge it- and I certainly don’t want to discourage contribution

**Comment by mboudreau** [comment]
Yeah, I think Tim is correct on this. Love the relevant comedy though ;)

**Comment by AndyGee** [comment]
So what you're saying is that if I get this pr merged at the Oxford Dictionaries then it's a green light? Awesome! - Seriously, I promise to not throw my teddy in the corner if you close ;-)

**Comment by mboudreau** [comment]
@AndyGee lol, keep the humor alive my friend, we're going to need it for what's coming up for the UK :P

Thanks for the PR, but I think we're close it.  I must appreciate the laugh, but not everyone might get it and we'd like to keep things clear and concise if possible.

Cheers.

**Pull request closed without merging**
