### PR TITLE
Gitbook cn

### PR DESCRIPTION
**Pull request by wldandan**
Hi pact-foundation team, 
Thanks for building good API testing framework - Pact. It is really awesome.
I am Lei from China. Fortunately, I worked with @bethesque for some days when I was a ThoughtWorks Consultant working for REA. 
Right now, I am recommending PACT in China Microservices Community as one of API testing framework. I would like to translate pact official documentation into Chinese version, so raised the PR. Is it ok for foundation team to merge it? or I can create a new repo and send PR later when translation version is ready. :)

### CODE REVIEW

**Comment by mefellows** [comment]
This is a great idea, we'll need to do a bit of thinking / research into how we release the Chinese site next to the English version.

What are you currently thinking? Separate (sub)domain, path-based etc.?

The PR is way too big at the moment for me to see what is happening.

**Comment by mboudreau** [comment]
Wow, that's great initiative. Thank you so much for doing all this work.
Next time, don't hesitate to contact us first to see how we can help or
provide guidance.

We just had a meeting last Friday about the website in general and changes
that are to happen. You bring up a very good point that even though pact
supports many programming languages, it doesn't support many human
languages. I think removing the barriers of entry for developers to use
this technology is crucial for its adoption.

We'll be reviewing how we can accommodate multiple languages within our
documentation and our website. We would love for you to help us become a
multilingual organisation. If you don't mind, we will contact you to get
your opinion on how to improve our website. Of course, we would be glad to
give you credit for all your hard work :)

Let's discuss this further soon. Cheers.

**Comment by wldandan** [comment]
Hey mefellows

It is not reasonable for you guys to merge PR with Chinese content, forget the gitbook-cn branch right now :)
To make it simple, we can start it by followings:
* Separate [repo](https://github.com/wldandan/pact-reference-guide-zh) 
* Separate [domain](pact.net.cn) (I did not bind it with gitbook right now)
* Add the reference in the website footer. I can open a PR for the changes later when it is avaliable. 

Does it make sense?

**Comment by mefellows** [comment]
Seems like a great starting point @wldandan, again, thanks for your efforts!

**Comment by bethesque** [comment]
Thanks @wldandan!

**Comment by tongzh** [comment]
Finally we have completed this and worked out the site [www.pact.net.cn](https://www.pact.net.cn) mentioned in https://github.com/pact-foundation/pact-foundation.github.io/issues/26

**Comment by TimothyJones** [comment]
Closing this, per the comment from @wldandan. Feel free to open another one if there's something you'd like us to merge.

**Pull request closed without merging**
