### PR TITLE
Attempting to clarify the steps when tagging a pact

### PR DESCRIPTION
**Pull request by jameshd**
My attempt to describe the workflow when getting new consumer fields added to a provider.

### CODE REVIEW

**Comment by TimothyJones** [comment]
Thanks for this!

I’ve been intentionally removing bolded sentences in the text body- I think if there is an important point that needs highlighting from the rest of the paragraph, it more indicates a paragraph that needs restructuring.

Do you think the paragraphs could read well without the extra bolding? If not, is there a way you’d like to split the paragraphs so the important point is clear in each one without bolding?

**Comment by TimothyJones** [comment]
Another comment- is there a better way to express “mainline”? I don’t think we’ve used the word elsewhere in the docs.

As an aside- reading this bit of the document again, I think we should better highlight that local verification really just means “without publishing the verification”. Of course, that doesn’t have to be in this PR :)

**Comment by jameshd** [comment]
Hey, I'll happily remove the bold text. I think you're right, maybe it does need some restructuring - Ideally a diagram... :smile: 

re the mainline/master I think you almost need a term that isn't related to version control, I think it introduces confusion - that's why I mentioned 'stable'. The main piece I missed was that you merge the provider first. I had in my head that it's consumer driven development, ergo you merge the consumer side first. It was only when I closely studied the docs that I spotted this parts I've bolded and the :bulb: went on! :smile:

**Comment by bethesque** [comment]
Thanks for you work on this @jameshd. I agree that if a point is important enough to bold, then then we should probably find another way of emphasising the point.

**Comment by bethesque** [comment]
Oh, it's already done. I was looking at an out of date page. Merging.

**Pull request merged**
