### PR TITLE
Making it clearer that the query params must be a string

### PR DESCRIPTION
**Pull request by rikkiprince**

### CODE REVIEW

**Comment by mefellows** [comment]
Thanks, yes query _strings_  (it's in the name!) does tend to confuse some people.

**Comment by TimothyJones** [comment]
Are people sometimes putting objects in? If that’s the confusion, we could also support it.

**Comment by mefellows** [comment]
In Pact JS you can supply either a string or an object. I think it's implementation specific.

I recall seeing a few issues where people were trying to do matchers over integers/floats (e.g. `like(27)` when it should be `regex({generate: "27", match: "\\d"})`.

**Comment by bethesque** [comment]
If you provide a query string, it must be already url encode. If you provide a query object, then the encoding will be done for you.

**Comment by rikkiprince** [comment]
The thing that caught my colleague out was an integer. I think it's because people tend to concatenate those into the query string, they expect the type conversion to happen automatically.

He figured it out by trial and error, but couldn't understand why until we found the documentation saying it had to be URL encoded. I think it's one step removed that if it's URL encoded then it must be a string, and just straight up stating it must be a string helps everyone get there quicker :-)

Thanks for your consideration and discussion folks!

**Pull request merged**
