### PR TITLE
replace broken links

### PR DESCRIPTION
**Pull request by Thomblin**
This PR replaces some broken links to https://github.com/pact-foundation/pact_broker/wiki/

I was not able to update the html files in ./_book
What is the correct command and gitbook version?

references: 
pact-foundation/pact_broker#281

### CODE REVIEW

**Comment by mefellows** [comment]
Thanks @Thomblin. I run `gitbook serve` locally, which starts a server on `localhost:4000`.

This is the output of `gitbook version`:

```
CLI version: 2.3.2
GitBook version: 3.2.3
```

**Comment by Thomblin** [comment]
@mefellows Are ypu able to run gitbook build as well?

**Comment by mefellows** [comment]
Yes, it does whinge about a plugin (prism) not being there, but for all intents and purposes of checking it works for me. I haven't had the need to run build.

**Comment by Thomblin** [comment]
Ok. I have no idea what the purpose of. /_book is

**Comment by YOU54F** [comment]
Thanks for this @Thomblin 

I think this is no longer needed as the docs code has moved to https://github.com/pact-foundation/docs.pact.io and I've just fixed a load of broken links 👍🏾 

Will close now, if you see any more feel free to reach out

**Pull request closed without merging**
